version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: liquidation
    secrets:
      - db_password
    ports:
      - '5432:5432'
    volumes:
      - data_postgres:/var/lib/postgresql/data

volumes:
  data_postgres:
    driver: local

secrets:
  db_password:
    file: db_password.txt
